# docker-compose.yml

version: '3.8'
name: ${PROJECT_NAME:-esp32-sensors}
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=gtga
      - POSTGRES_PASSWORD=dragon
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
